#!/usr/bin/python3


import sys


def is_prime(n):
    if n <= 1:
        return False
    if n <= 3:
        return True
    if n % 2 == 0 or n % 3 == 0:
        return False
    i = 5
    while i * i <= n:
        if n % i == 0 or n % (i + 2) == 0:
            return False
        i += 6
    return True

def find_prime_factors(n):
    factors = []
    for i in range(2, n // 2 + 1):
        if n % i == 0 and is_prime(i) and is_prime(n // i):
            factors.append((i, n // i))
            break
    return factors

def main(file_path):
    with open(file_path, 'r') as file:
        number = int(file.readline().strip())
    
    factor_pairs = find_prime_factors(number)
    for pair in factor_pairs:
        print(f"{number}={pair[0]}*{pair[1]}")

if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("Usage: factors <file>")
        sys.exit(1)

    file_path = sys.argv[1]
    main(file_path)
